# Generated by Django 5.2.7 on 2025-10-17 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NbaUserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Receive notifications for NBA game predictions')),
                ('favorite_conference', models.CharField(blank=True, choices=[('east', 'Eastern Conference'), ('west', 'Western Conference')], help_text='Preferred NBA conference for highlights', max_length=10)),
                ('show_player_stats', models.BooleanField(default=True, help_text='Show detailed player statistics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nba_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NBA user preferences',
                'verbose_name_plural': 'NBA user preferences',
            },
        ),
    ]
