# Generated by Django 5.2.7 on 2025-10-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0002_nbateam_nbaplayer_scheduledgame'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NbaPlayer',
        ),
        migrations.DeleteModel(
            name='NbaTeam',
        ),
    ]
