# Generated by Django 5.2.7

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predictions', '0003_remove_scheduledgame_tip_type_delete_nbaplayer_and_more'),
    ]

    operations = [
        # Demo app doesn't have any models - it uses the generic prediction models
    ]
