# Generated by Django 5.2.7 on 2025-10-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoPseudoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Demo Event',
                'verbose_name_plural': 'Demo Events',
                'db_table': '_demo_pseudo',
                'managed': False,
            },
        ),
    ]
