# Generated by Django 5.2 on 2025-11-19 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predictions', '0012_alter_usertip_lock_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verband_name', models.CharField(help_text='Name of the Verband', max_length=200)),
                ('verband_id', models.CharField(help_text='External ID from SLAPI', max_length=100)),
                ('league_name', models.CharField(help_text='Name of the league', max_length=200)),
                ('league_id', models.CharField(help_text='External ID from SLAPI', max_length=100)),
                ('club_search_term', models.CharField(help_text="The search term used to find the club (e.g., 'Bierden-Bassen')", max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether to actively track matches for this league')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tracked league',
                'verbose_name_plural': 'Tracked leagues',
                'ordering': ['verband_name', 'league_name'],
                'unique_together': {('verband_id', 'league_id')},
            },
        ),
        migrations.CreateModel(
            name='DbbMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_match_id', models.CharField(help_text='Unique match ID from SLAPI', max_length=100, unique=True)),
                ('match_date', models.DateTimeField(help_text='Match start time')),
                ('home_team', models.CharField(help_text='Home team name', max_length=200)),
                ('away_team', models.CharField(help_text='Away team name', max_length=200)),
                ('venue', models.CharField(blank=True, help_text='Venue/location', max_length=200)),
                ('league_name', models.CharField(help_text='League name for context', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional match data from SLAPI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tip_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dbb_matches', to='predictions.tiptype')),
                ('tracked_league', models.ForeignKey(blank=True, help_text='Reference to the tracked league', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='dbb.trackedleague')),
            ],
            options={
                'verbose_name': 'DBB match',
                'verbose_name_plural': 'DBB matches',
                'ordering': ['match_date'],
            },
        ),
        migrations.CreateModel(
            name='TrackedTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(help_text='Full team name from API', max_length=200)),
                ('team_id', models.CharField(blank=True, help_text='External ID from SLAPI (if available)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether to track matches for this team')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracked_league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='dbb.trackedleague')),
            ],
            options={
                'verbose_name': 'Tracked team',
                'verbose_name_plural': 'Tracked teams',
                'ordering': ['team_name'],
                'unique_together': {('tracked_league', 'team_name')},
            },
        ),
    ]
