# Generated by Django 5.2 on 2025-11-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbbmatch',
            name='venue',
            field=models.CharField(blank=True, help_text='Venue/location', max_length=200, null=True),
        ),
    ]
