# Generated by Django 5.2 on 2025-11-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbb', '0002_alter_dbbmatch_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedteam',
            name='logo',
            field=models.CharField(blank=True, help_text="Logo filename (e.g., 'bierden-bassen.svg') from static/dbb/ directory", max_length=200),
        ),
    ]
