# Generated by Django 5.2 on 2025-11-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbb', '0003_trackedteam_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedteam',
            name='logo',
            field=models.CharField(blank=True, help_text='Logo filename (optional - will auto-discover from static/dbb/ if blank)', max_length=200),
        ),
    ]
